name: Node.js CI

on:
  push:
    branches: [ develop, main ]
  pull_request:
    branches: [ develop, main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install

      - name: Start server
        run: nohup npm start &

      - name: Wait for server to be ready
        run: |
          for i in {1..10}; do
            nc -z localhost 3000 && echo "Server is up!" && exit 0
            sleep 1
          done
          echo "Server did not start in time" && exit 1

      - name: Run tests
        run: npm test
